### ISSUE TITLE
Is "heating_circuits_0_heating_curve_shift" really read only in the API 

### ISSUE THREAD

**Issue by troem** [rtuck99/openhab-binding#61]
Could it be changed to be writable?

**Comment by rtuck99** [comment]
It's not read-only however it does have a different method for changing as the slope and the shift have to be applied in the same API call. 
Thus far it has not been implemented as I could not see much demand for it, seeing as it's something that in general you are supposed to set once on commissioning of the system, and not to change in day-to-day use. Also whereas the Vicare app gives you a nice graph with a line on it so that you can see the heating curve and be sure that it is adequate across the full temperature range, you don't get any such indication in OpenHAB.

Do you have a particular use case in mind?

**Comment by troem** [comment]
Thank you for your reply: My use-case is Energy Management. With a hourly electricity plan and a solar plant on my roof, I want to increase / decrease temperature during cheap/expensive times for the heat-pump.

**Comment by troem** [comment]
Hi, do you think it might be possible for you to implement this feature in the near future? I am open to help with testing or any other support you might need, please let me know.

**Comment by svenb1234** [comment]
I second the feature request. Especially in autumn the optimal slope and shift can vary from day to day, i.e. has to be managed by some kind of logic.

**Comment by MaTr74** [comment]
I would vote for this too. I like to have different curves for day, evening and night. The night shift is done by night setback. I could change the shift by setting the operating programs normal temperature, but this is slightly coarser than heating curve shift. So with heating curve shift I can adjust the curve in smaller steps.

**Comment by rtuck99** [comment]
These use cases are not what the heating curve is for. The heating curve defines the behaviour of the weather compensation system and set the responsiveness of the flow temperature to changes in the outdoor temperature.

The correct curve is defined by the thermal properties of the building, and does not change on a daily or hourly basis.

At most it is something you might adjust _slightly_ on a seasonal basis, and you are supposed to determine the correct curve by observing the response of the entire system over a range of outdoor temperatures. After one heating season you should have found the correct curve and just leave it, unless your house undergoes renovation that changes the heat loss characteristics.

**Comment by svenb1234** [comment]
Everybody knows that the curve is imperfect. First, because there cannot be a single perfect curve for all seasons, i.e. the curve that works well in deep winter will have issues in the change from/to autumn.

Second, sun in winter or no sun changes the need for heat quite significantly if you have a lot of windows. Working with the same curve wastes energy because it only considers the outside temperature, not the inside temperature. Your heating will run with a too high temperature and either it is wasted because the valves in the rooms close or the house will become too warm.

Smart home is about being able to adjust better than in the old times, because of considering more sensor data.

Anyway, those that want to have a smart heating system that saves CO2 and money can use the smarthome/j Viessmann binding. It supports setting the slope and shift, because Viessmann supports it, because it makes sense.

**Comment by MaTr74** [comment]
> At most it is something you might adjust _slightly_ on a seasonal basis, and you are supposed to determine the correct curve by observing the response of the entire system over a range of outdoor temperatures. 

Isn't that an exciting opportunity for an automated process?

> After one heating season you should have found the correct curve

There is a plenty off parameters, not only slope and shift, that influence the thermal beviour of your building, like sun, wind, rain, temperature of the soil, the weather before etc. Futhermore, your temperature feeling in the morning, at noon, in the evening, after a shower, after sitting for hours at the table may influence your choice of the target temperature. Unfortunately, your heating curve is only made for one target temperatur for the whole building. What is, if you decide to heat only one room over day and other rooms at evening? Is the best heating curve the same? One thing is clear: you are leaving potential along the way.  

But to make it clear. I appreciate your work. We can be glad that there are developers like you who implement functions in their spare time that we can use. And you don't have to implement every function that other wishes.

> These use cases are not what the heating curve is for.

:man_shrugging: 
![everyone-should-use-git](https://github.com/user-attachments/assets/e6e86b64-b153-4151-ba85-48310b0048e8)
